# Generated by Django 2.0 on 2017-12-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos_perfil/'),
        ),
    ]
